os: Windows
language: python
python:
  - "3.10"
install: "pip install -r requirements.txt"
script:
  - sonar-scanner
after_success:
  - coveralls
addons:
  sonarcloud:
    organization: jennajungsungoh