language: python
python:
  - "3.9"
language: node_js
node_js:
  - "14"
language: java
jdk:
  - openjdk11
install: "pip install -r requirements.txt"
script:
  - sonar-scanner
after_success:
  - coveralls
addons:
  sonarcloud:
    organization: jennajungsungoh