rmdir /Q /S .vs
rmdir /Q /S  libs\dependencies\giflib\.vs
rmdir /Q /S  libs\dependencies\giflib\x64
rmdir /Q /S  libs\dependencies\libjpeg\.vs
rmdir /Q /S  libs\dependencies\libjpeg\x64
rmdir /Q /S  libs\dependencies\liblept\liblept-DLL\.vs
rmdir /Q /S  libs\dependencies\liblept\liblept-DLL\x64
rmdir /Q /S  libs\dependencies\liblept\liblept-static\.vs
rmdir /Q /S  libs\dependencies\liblept\liblept-static\x64
rmdir /Q /S  libs\dependencies\libpng\.vs
rmdir /Q /S  libs\dependencies\libpng\x64
rmdir /Q /S  libs\dependencies\libtiff\.vs
rmdir /Q /S  libs\dependencies\libtiff\x64
rmdir /Q /S  libs\dependencies\zlib\.vs
rmdir /Q /S  libs\dependencies\zlib\x64
rmdir /Q /S  libs\dependencies\tesseract\libtesseract-DLL\.vs
rmdir /Q /S  libs\dependencies\tesseract\libtesseract-DLL\x64
rmdir /Q /S  libs\dependencies\tesseract\libtesseract-static\.vs
rmdir /Q /S  libs\dependencies\tesseract\libtesseract-static\x64
rmdir /Q /S  libs\libopenalpr\x64
rmdir /Q /S  libs\libopenalpr\.vs
rmdir /Q /S  alpr\.vs
rmdir /Q /S  alpr\x64
rmdir /Q /S  x64
rmdir /Q /S  lgdemo\.vs
rmdir /Q /S  lgdemo\x64
rmdir /Q /S  OpenCVDeviceEnumerator\.vs
rmdir /Q /S  OpenCVDeviceEnumerator\x64
rmdir /Q /S  loaddb\.vs
rmdir /Q /S  loaddb\x64
rmdir /Q /S  server\.vs
rmdir /Q /S  server\x64