# Generated by Django 4.0.5 on 2022-06-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpr', '0004_vehicle_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['id']},
        ),
    ]
