# Generated by Django 4.0.5 on 2022-06-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpr', '0006_alter_vehicle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='session_id',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
