# Generated by Django 4.0.5 on 2022-06-26 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpr', '0007_vehicle_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='session_id',
            new_name='session_key',
        ),
    ]
