# Generated by Django 4.0.5 on 2022-06-26 11:56

import alpr.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alpr', '0008_rename_session_id_vehicle_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(upload_to=alpr.models.get_upload_path),
        ),
    ]
