# Generated by Django 4.0.5 on 2022-06-30 10:16

import alpr.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alpr', '0010_vehicle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='captured_frame',
            field=models.FileField(default=1, upload_to=alpr.models.get_upload_tmp_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='maker',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_addr',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_birth',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_zip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_number_likely',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='regist_exp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='yom',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('status', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
