# Generated by Django 4.0.5 on 2022-07-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpr', '0011_vehicle_captured_frame_vehicle_color_vehicle_maker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_server', models.CharField(max_length=256)),
            ],
        ),
    ]
